[package]
name = "my_jepa"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.32"
rand = "0.8"
regex = "1.0"
metal = "0.28"
objc = "0.2"
cocoa = "0.25"

[target.'cfg(target_os = "macos")'.dependencies]
metal = "0.28"
